dataframes:
  data_EB:
    df_data_EB_train.h5
  data_EE:
    df_data_EE_train.h5
  mc_EB:
    df_mc_EB_train.h5
  mc_EE:
    df_mc_EE_train.h5

variables:
  ['probeCovarianceIeIp','probeS4','probeR9','probePhiWidth','probeSigmaIeIe','probeEtaWidth']

year:
  2017

workDir:
  /vols/cms/jwd18/qRCSamples/dataframes/UL/2017/

weightsDir:
  weights_qRC_SS_UL

outDir:
  weights_qRC_SS_UL/final/
